## Building docker image
## Pushing docker image to docker hub
## SSH into VM and start new image

name: Deploy the server
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.server
          push: true
          tags: saatvik10/monorepo-dc-server:${{ github.sha }}

      - name: Deploy to the VM
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/ssh_key
          chmod 600 ~/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key root@65.0.110.118 << 'EOF'
            docker stop user_server || true
            docker rm user_server || true
            docker pull saatvik10/monorepo-dc-server:${{ github.sha }}
            docker run --name user_server -d -p 8080:8080 saatvik10/monorepo-dc-server:${{ github.sha }}
          EOF

          # - run: |
          # echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          # mkdir -p /home/runner/.ssh
          # ls /home/runner/.ssh
          # touch /home/runner/.ssh/known_hosts
          # echo "${{ secrets.KNOWN_HOSTS }}" &> /home/runner/.ssh/known_hosts
          # chmod 700 /home/runner/ssh_key
          # ssh -o StrictHostKeyChecking=no -i ~/ssh_key root@64.227.147.124 -t "docker stop user_backend && docker run --name user_backend -d -p 8080:8080 100xdevs/user-app-backend:${{ github.sha }}"
