name: Deploy web
on:
  push:
    branches: [ main ]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push 
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.web
          build-args: | 
            - DATABASE_URL=${{ secrets.DATABASE_URL }}
          push: true
          tags: saatvik10/monorepo-dc-web:${{ github.sha }}

      - name: Deploy to the VM
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/ssh_key
          chmod 600 ~/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key root@65.0.110.118 << 'EOF'
            docker stop user_web || true
            docker rm user_web || true
            docker pull saatvik10/monorepo-dc-web:${{ github.sha }}
            docker run --name user_web -d -p 3000:3000 saatvik10/monorepo-dc-web:${{ github.sha }}
          EOF
